import { services, work, origin } from './content';
import { Booking, Tracking } from './site-interactions';
const schema = {'@context':'https://schema.org','@graph':[
{'@type':'ProfilePage','@id':origin+'/#profile',url:origin,name:'Manas Dewari — Co-founder & CTO at Zryth',mainEntity:{'@id':origin+'/#person'}},
{'@type':'Person','@id':origin+'/#person',name:'Manas Dewari',jobTitle:'Co-founder & CTO',url:origin,image:origin+'/manas-dewari-960.webp',description:'Manas Dewari is Co-founder & CTO at Zryth Solutions Pvt. Ltd., working across enterprise automation, Agentic AI and product engineering.',worksFor:{'@id':'https://zryth.com/#organization'},knowsAbout:['Agentic AI','Enterprise automation','Business process automation','Product engineering','Manufacturing technology','Finance automation','Education technology']},
{'@type':'Organization','@id':'https://zryth.com/#organization',name:'Zryth Solutions Pvt. Ltd.',url:'https://zryth.com'}]};
export default function Home(){return <>
<Tracking/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<a className="skip" href="#main">Skip to content</a>
<header className="header"><a href="#home" className="wordmark" aria-label="Manas Dewari home">manas<span>.</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#about">About</a><a href="#expertise">What I do</a><a href="#work">Work</a><a href="#perspective">Perspective</a></nav><a className="button header-cta" href="#book" data-event="book_call_clicked">Book a call</a><details className="mobile-menu"><summary aria-label="Navigation menu">Menu</summary><nav aria-label="Mobile navigation"><a href="#about">About</a><a href="#expertise">What I do</a><a href="#work">Work</a><a href="#perspective">Perspective</a></nav></details></header>
<main id="main"><section id="home" className="hero wrap"><div className="eyebrow">MANAS DEWARI <span>CO-FOUNDER & CTO AT ZRYTH</span></div><h1>Intelligent systems.<br/>Less manual work.<br/><em>More room to grow.</em></h1><div className="hero-bottom"><p>I work with businesses to turn operational problems into practical software, automation and Agentic AI systems.</p><div className="hero-actions"><a className="button" href="#book" data-event="book_call_clicked">Book a conversation</a><a className="text-link" href="#work">Explore my work</a></div></div><div className="hero-line"><span>TECHNOLOGY WITH A BUSINESS PURPOSE</span><span>Manas Dewari / Zryth Solutions</span></div></section>
<div className="experience"><div className="wrap experience-inner"><span>EXPERIENCE ACROSS</span><p>Manufacturing</p><p>Finance</p><p>Education</p><a href="https://zryth.com" target="_blank" rel="noopener noreferrer" data-event="zryth_clicked">Meet Zryth</a></div></div>
<section id="about" className="wrap about section"><div className="about-profile"><div className="section-label">01 / ABOUT</div><img className="portrait" src="/manas-dewari-960.webp" srcSet="/manas-dewari-480.webp 480w, /manas-dewari-960.webp 960w" sizes="(max-width: 767px) calc(100vw - 48px), 350px" width="960" height="1280" loading="lazy" decoding="async" alt="Manas Dewari, Co-founder and CTO at Zryth Solutions, beside a Zryth mill software display"/></div><div><h2>A founder’s perspective.<br/>An engineer’s approach.</h2><p className="lead">I’m Manas Dewari, Co-founder & CTO at Zryth Solutions Pvt. Ltd.</p><p>My work sits at the intersection of technology, operations and business. I start by understanding how an organisation works, where manual effort builds up and what a useful system needs to change.</p><p>At Zryth, I work across product strategy, engineering, enterprise automation, Agentic AI and client solution design.</p><a className="text-link" href="https://zryth.com/products" target="_blank" rel="noopener noreferrer" data-event="products_clicked">Explore Zryth’s products</a></div></section>
<section id="expertise" className="expertise section"><div className="wrap"><div className="section-heading"><div><div className="section-label">02 / WHAT I DO</div><h2>From operational friction<br/>to useful systems.</h2></div><p>Technology choices follow the problem.<br/>The outcome stays in focus.</p></div><div className="service-grid">{services.map(([title,desc],i)=><article key={title}><span className="service-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
<section id="work" className="wrap section work"><div className="section-heading"><div><div className="section-label">03 / SELECTED WORK</div><h2>Real processes.<br/>Practical applications.</h2></div><p>A closer look at the problems<br/>I work on with the Zryth team.</p></div>{work.map(item=><article className="work-row" key={item.number}><div className="work-intro"><span className="work-tag">{item.number} / {item.industry}</span><h3>{item.title}</h3></div><div className="work-details"><div><h4>The problem</h4><p>{item.problem}</p></div><div><h4>The approach</h4><p>{item.solution}</p></div><div><h4>Technology</h4><p>{item.technology}</p></div><div><h4>Business purpose</h4><p>{item.impact}</p></div></div></article>)}</section>
<section id="perspective" className="perspective section"><div className="wrap"><div className="section-label">04 / HOW I THINK</div><blockquote>“Technology should remove operational friction — not create another tool people have to manage.”</blockquote><div className="perspective-bottom"><span>Manas Dewari</span><p>The most useful AI solutions begin with understanding the process. I focus first on how work happens, where time is lost and where automation can meaningfully improve the system.</p></div></div></section>
<section id="book" className="wrap section booking"><div><div className="section-label">05 / LET’S CONNECT</div><h2>Start with<br/><em>the problem.</em></h2><p>Exploring AI, automating an internal workflow, building a product or modernising a system? Let’s talk about what you’re trying to solve.</p><div className="conversation-topics"><span>Enterprise & operations</span><span>Product & engineering</span><span>Technology partnerships</span></div></div><Booking/></section></main>
<footer className="wrap footer"><div><a href="#home" className="wordmark">manas<span>.</span></a><p>Manas Dewari<br/>Co-founder & CTO<br/>Zryth Solutions Pvt. Ltd.</p></div><div className="footer-links"><a href="https://zryth.com" target="_blank" rel="noopener noreferrer" data-event="zryth_clicked">Zryth website</a><a href="https://zryth.com/products" target="_blank" rel="noopener noreferrer" data-event="products_clicked">Zryth products</a><a href="https://calendly.com/manas-zryth" target="_blank" rel="noopener noreferrer" data-event="book_call_clicked">Book on Calendly</a></div><div className="footer-note">© {new Date().getFullYear()} Manas Dewari<br/>Built around useful conversations.</div></footer>
</>}
